import PriceBased from "../assets/images/Price-based.svg";
import VolumeBased from "../assets/images/Volume-based.svg";
import VolatilityBased from "../assets/images/Volatility-based.svg";
import Statistical from "../assets/images/Statistical.svg";
import MomentumBased from "../assets/images/Time-based.svg";
import CombinedSignals from "../assets/images/Combined_Signals.svg";

import crossing from "../assets/icons/crossing.svg";
import crossingUp from "../assets/icons/crossing_up.svg";
import crossingDown from "../assets/icons/crossing_down.svg";
// import enteringChannel from "../assets/icons/entering_channel.svg";
// import exitingChannel from "../assets/icons/exiting_channel.svg";
import MovingUp from "../assets/icons/MovingUp.svg";
import MovingDown from "../assets/icons/MovingDown.svg";
import MovingPercentageUp from "../assets/icons/MovingPercentageUp.svg";
import MovingPercentageDown from "../assets/icons/MovingPercentageDown.svg";

export const SEO_DATA = {
  home: {
    title:
      "Trading Platform with Real-Time, Actionable Insights - Tradexpert.ai",
    description:
      "TradeXpert.ai, your all-in-one trading platform offering exclusive insider signals, AI-driven insights, customized chart patterns, & innovative trading strategies.",
    keywords: [
      "trading platform",
      "forex trading",
      "cryptocurrency trading",
      "AI trading insights",
      "chart patterns",
      "trading strategies",
      "insider signals",
    ],
  },
  news: {
    title:
      "TradeXpert.ai News: Daily Expert Insights on Forex, Crypto, and Trading",
    description:
      "Stay informed with TradeXpert.ai's latest updates on forex, cryptocurrency, and trading markets. Access daily expert insights, market analysis, and platform news to enhance your trading strategies.",
    keywords: [
      "forex news",
      "crypto news",
      "trading insights",
      "market updates",
      "daily trading analysis",
      "expert trading news",
    ],
  },
  feature: {
    title: "Our Features - TradeXpert.ai",
    description:
      "Explore TradeXpert.ai's cutting-edge tools, comprehensive market insights, and educational resources designed to elevate your trading experience.",
    keywords: [
      "trading tools",
      "trading features",
      "market insights",
      "trading platform",
      "trading resources",
      "trading strategies",
    ],
  },
  learning: {
    title: "TradeXpert.ai Learning Hub: Master Essential Trading Indicators",
    description:
      "Enhance your trading skills with TradeXpert.ai's Learning Hub. Explore comprehensive guides on essential trading indicators, from basic concepts to advanced strategies, and make informed market decisions.",
    keywords: [
      "trading indicators",
      "trading education",
      "learn trading",
      "technical analysis",
      "trading strategies",
      "market indicators",
      "forex education",
    ],
  },
  pricing: {
    title: "Pricing - TradeXpert.ai",
    description:
      "Explore TradeXpert.ai flexible pricing plans tailored to your trading needs. Access advanced tools, real-time market data, and educational resources to enhance your trading strategies.",
    keywords: [
      "pricing plans",
      "trading subscription",
      "trading tools",
      "advanced market data",
      "real-time data",
      "affordable pricing",
      "trading platform pricing",
    ],
  },
  "about-us": {
    title: "About Us - Tradexpert.ai",
    description:
      "Discover how TradeXpert.ai combines expert market analysis with state-of-the-art charting tools to help traders master the markets with confidence and clarity.",
    keywords: [
      "about TradeXpert.ai",
      "trading platform",
      "expert analysis",
      "market tools",
      "trading solutions",
      "charting tools",
    ],
  },
  faq: {
    title: "FAQ - TradeXpert.ai",
    description:
      "Find clear answers to common questions about TradeXpert.ai's features, pricing, and support.",
    keywords: [
      "TradeXpert FAQ",
      "trading platform support",
      "platform questions",
      "trading help",
      "frequently asked questions",
      "customer support",
    ],
  },
};

export const defaultPatterns = {
  singleCandlesticks: [
    { name: "doji", label: "Doji" },
    { name: "hammer", label: "Hammer" },
    { name: "hanging_man", label: "Hanging Man" },
    { name: "shooting_star", label: "Shooting Star" },
    { name: "marubozu", label: "Marubozu" },
  ],
  doubleCandlesticks: [
    { name: "engulfing_pattern", label: "Engulfing Pattern" },
    { name: "harami_pattern", label: "Harami Pattern" },
    { name: "doji_star", label: "Doji Star" },
  ],
  tripleCandlesticks: [
    { name: "morning_star", label: "Morning Star" },
    { name: "evening_star", label: "Evening Star" },
  ],
  basicPatterns: [{ name: "bullish_flag", label: "Bullish Flag" }],
  advancedPatterns: [{ name: "head_and_shoulder", label: "Head and Shoulder" }],
  harmonicPatterns: [{ name: "gartley", label: "Gartley" }],
};

export const TAGS = [
  "Nifty",
  "Sensex",
  "Dow Jones",
  "Nasdaq",
  "S&P 500",
  "FTSE 100",
  "DAX",
  "Nikkei 225",
  "Hang Seng",
  "Reliance Industries",
  "TCS",
  "Adani",
  "HDFC",
  "Infosys",
  "Apple",
  "Microsoft",
  "Amazon",
  "Google",
  "Meta",
  "Tesla",
  "Nvidia",
  "SEBI",
  "Indian Mutual Funds",
  "Electric Vehicles",
  "Semiconductors",
  "Banking Sector",
  "IT Sector",
  "Healthcare Sector",
  "Energy Sector",
  "Manufacturing",
  "Bitcoin",
  "Dogecoin",
  "Ethereum",
  "Crypto",
  "US Dollar",
  "USD INR",
  "EUR USD",
  "USD JPY",
  "GBP USD",
  "Forex",
  "Crude Oil",
  "Gold",
  "Silver",
  "Oil and Gas",
  "US Market",
  "Indian Market",
  "European Markets",
  "Asian Markets",
  "ETF",
  "Futures Market",
  "Options Trading",
  "Derivatives Market",
  "US Treasury",
  "Global Economy",
  "Interest Rates",
  "Inflation",
  "Federal Reserve",
  "RBI",
  "icici",
  "HUL",
  "infosys",
  "ITC",
  "SBI",
  "Airtel",
  "Bajaj Finance",
  "LIC",
  "Larsen & Toubro",
  "Kotak",
  "Axis Bank",
  "Adani Enterprises",
  "Adani Ports",
  "Apollo Hospitals",
  "Asian Paints",
  "Axis Bank",
  "Bajaj Auto",
  "Bajaj Finance",
  "Bajaj Finserv",
  "Bharti Airtel",
  "BPCL",
  "Britannia",
  "Cipla",
  "Coal India",
  "Divis Labs",
  "Dr Reddy's Labs",
  "Eicher Motors",
  "Grasim",
  "HCL Tech",
  "HDFC Bank",
  "Hero MotoCorp",
  "Hindalco",
  "HUL",
  "ICICI Bank",
  "IndusInd Bank",
  "Infosys",
  "ITC",
  "JSW Steel",
  "Kotak Mahindra Bank",
  "L&T",
  "M&M",
  "Maruti Suzuki",
  "Nestle India",
  "NTPC",
  "Oil & Natural Gas Corporation",
  "Power Grid Corporation",
  "Reliance Industries",
  "SBI",
  "SBI Life Insurance",
  "Shriram Finance",
  "Sun Pharma",
  "Tata Consumer Products",
  "Tata Motors",
  "Tata Steel",
  "TCS",
  "Tech Mahindra",
  "Titan",
  "UltraTech Cement",
  "UPL",
  "Wipro",
  "LTIMindtree",
  "asian paints",
  "HCL",
  "Maruti",
  "Sun Pharma",
  "Tata Motors",
  "Adani",
  "UltraTech",
  "Titan",
  "Nestle",
  "Power Grid",
  "NTPC",
  "Wipro",
  "Adani Ports",
  "Grasim",
  "Bajaj Auto",
  "JSW Steel",
  "Tata Steel",
  "Adani Green",
  "Britannia",
  "cipla",
  "divis labs",
  "eicher motors",
  "Dr Reddy",
  "Hindalco",
  "Shree Cement",
  "HDFC Life",
  "Hero MotoCorp",
  "Berger Paints",
  "dabur",
  "havells",
  "UPL",
  "SRF",
  "Indigo",
  "Marico",
  "MRF",
  "Pidilite",
  "Apple",
  "Microsoft",
  "amazon",
  "nvidia",
  "alphabet",
  "meta",
  "tesla",
  "broadcom",
  "pepsico",
  "costco",
  "intel",
  "cisco",
  "amd",
  "adobe",
  "netflix",
  "qualcomm",
  "texas instruments",
  "intuit",
  "booking",
  "starbucks",
  "airbnb",
  "micron",
  "applied materials",
  "moderna",
  "mondelez",
  "UnitedHealth",
  "goldman",
  "Home Depot",
  "McDonald",
  "visa",
  "boeing",
  "disney",
  "JPMorgan",
  "coca cola",
  "Johnson & Johnson",
  "amgen",
  "caterpillar",
  "chevron",
  "Cisco",
  "honeywell",
  "Intel",
  "merck",
  "nike",
  "salesforce",
  "UPS",
  "verizon",
  "Walgreen",
  "walmart",
  "SEBI",
  "SEC",
  "RBI",
  "IRDAI",
  "PFRDA",
  "NPCI",
  "IBBI",
  "FSDC",
  "ESMA",
  "ASIC",
  "MAS",
  "HKMA",
  "PBOC",
  "Bank of England",
  "European Central Bank",
  "Technical Analysis",
  "Fundamental Analysis",
  "Market Outlook",
  "Trading Strategies",
  "Market Sentiment",
  "Price Action",
  "Volume Analysis",
  "Market Trends",
  "Chart Patterns",
  "Support Resistance",
  "Moving Averages",
  "RSI Analysis",
  "MACD Analysis",
  "Momentum Indicators",
  "Volatility Index",
  "Credit Rating",
  "Stock Upgrades",
  "Stock Downgrades",
  "Buy Rating",
  "Sell Rating",
  "Hold Rating",
  "Strong Buy",
  "Strong Sell",
  "Price Target",
  "Analyst Commentary",
  "Research Reports",
  "Market Valuations",
  "Consensus Estimates",
  "Earnings Estimates",
  "Revenue Forecasts",
  "Stock Split",
  "Bonus Issue",
  "Rights Issue",
  "Share Buyback",
  "Dividend Announcement",
  "Mergers",
  "Acquisitions",
  "Demerger",
  "Corporate Restructuring",
  "Delisting",
  "IPO",
  "FPO",
  "OFS",
  "Block Deals",
  "Bulk Deals",
  "Nifty Bank",
  "Nifty IT",
  "Nifty Auto",
  "Nifty Pharma",
  "Nifty FMCG",
  "Nifty Metal",
  "Nifty Realty",
  "Nifty Energy",
  "Nifty Media",
  "BSE SmallCap",
  "BSE MidCap",
  "Nifty Midcap 100",
  "Nifty Smallcap 100",
  "Nifty Next 50",
  "India VIX",
  "Value Investing",
  "Growth Investing",
  "Dividend Investing",
  "Momentum Investing",
  "ESG Investing",
  "Impact Investing",
  "Thematic Investing",
  "Index Investing",
  "Factor Investing",
  "Contrarian Investing",
  "Day Trading",
  "Swing Trading",
  "Position Trading",
  "Arbitrage Trading",
  "Algorithmic Trading",
  "Quarterly Results",
  "Annual Results",
  "Management Commentary",
  "Business Expansion",
  "New Product Launch",
  "Market Share",
  "Competition News",
  "Industry Analysis",
  "Regulatory Compliance",
  "Legal Issues",
  "Corporate Governance",
  "Insider Trading",
  "Shareholding Pattern",
  "Promoter Activity",
  "FII Activity",
  "GDP Growth",
  "IIP Data",
  "CPI Inflation",
  "WPI Inflation",
  "Trade Balance",
  "Forex Reserves",
  "Current Account",
  "Fiscal Deficit",
  "Tax Collection",
  "Manufacturing PMI",
  "Services PMI",
  "Bank Credit Growth",
  "FDI Inflow",
  "Employment Data",
  "Consumer Confidence",
  "G20 Summit",
  "OPEC Meeting",
  "IMF Updates",
  "World Bank Report",
  "Trade Agreements",
  "Geopolitical News",
  "Climate Change",
  "Natural Disasters",
  "Pandemic Updates",
  "Political Elections",
  "Economic Sanctions",
  "Trade Wars",
  "Currency Crisis",
  "Market Crashes",
  "Economic Recovery",
  "Artificial Intelligence",
  "Machine Learning",
  "Blockchain",
  "Cloud Computing",
  "Edge Computing",
  "Internet of Things",
  "5G Technology",
  "6G Development",
  "Quantum Computing",
  "Cybersecurity",
  "Digital Transformation",
  "Big Data Analytics",
  "Extended Reality",
  "Green Technology",
  "Space Technology",
  "Electric Vehicles",
  "Renewable Energy",
  "Space Economy",
  "Digital Healthcare",
  "Biotech",
  "Agritech",
  "Cleantech",
  "Drone Technology",
  "Smart Cities",
  "Digital Banking",
  "Super Apps",
  "Gaming Industry",
  "Metaverse",
  "Web3",
  "Carbon Credits",
  "Trading Systems",
  "Settlement Cycles",
  "Margin Rules",
  "Circuit Filters",
  "Trading Hours",
  "Market Makers",
  "Broking Industry",
  "Depository Services",
  "Clearing Houses",
  "Exchange Updates",
  "Trading Platforms",
  "Market Access",
  "Risk Management",
  "Compliance Updates",
  "Trading Regulations",
  "Base Metals",
  "Natural Gas",
  "Crude Oil",
  "Precious Metals",
  "Agricultural Commodities",
  "Industrial Metals",
  "Energy Products",
  "Metal Index",
  "Commodity Index",
  "Oil Marketing",
  "Mining Sector",
  "Steel Industry",
  "Coal Industry",
  "Diamond Industry",
  "Textile Industry",
  "Startup Funding",
  "Venture Capital",
  "Angel Investing",
  "Unicorn Startups",
  "Startup IPOs",
  "Startup Valuations",
  "Founder News",
  "Innovation Hub",
  "Incubators",
  "Accelerators",
  "Seed Funding",
  "Series Funding",
  "Exit Strategy",
  "Startup Policy",
  "Tech Startups",
  "Government Bonds",
  "Corporate Bonds",
  "Treasury Bills",
  "Municipal Bonds",
  "Green Bonds",
  "Bond Yields",
  "Sovereign Debt",
  "Bond Trading",
  "Fixed Income",
  "Debt Market",
  "Credit Market",
  "High Yield Bonds",
  "Investment Grade Bonds",
  "International Bonds",
  "Bond ETFs",
  "Equity Funds",
  "Debt Funds",
  "Hybrid Funds",
  "Index Funds",
  "ETFs",
  "Large Cap Funds",
  "Mid Cap Funds",
  "Small Cap Funds",
  "Sectoral Funds",
  "International Funds",
  "Fund Managers",
  "SIP Investments",
  "Fund Performance",
  "Fund Ratings",
  "NFO",
  "PSU Banks",
  "PSU Energy",
  "PSU Defense",
  "PSU Insurance",
  "PSU Mining",
  "PSU Transport",
  "PSU Trading",
  "PSU Manufacturing",
  "PSU Oil Gas",
  "PSU Power",
  "PSU Steel",
  "PSU Telecom",
  "Maharatna PSUs",
  "Navratna PSUs",
  "PSU Privatization",
  "Roads Highways",
  "Railways",
  "Ports Shipping",
  "Airports Aviation",
  "Power Generation",
  "Power Distribution",
  "Water Infrastructure",
  "Smart Cities",
  "Urban Infrastructure",
  "Rural Infrastructure",
  "Digital Infrastructure",
  "Telecom Infrastructure",
  "Logistics Infrastructure",
  "Construction Sector",
  "Infrastructure Finance",
  "Market Capitalization",
  "PE Ratio",
  "PB Ratio",
  "EPS Growth",
  "Revenue Growth",
  "Profit Margins",
  "ROE",
  "ROCE",
  "Debt Equity Ratio",
  "Working Capital",
  "Free Cash Flow",
  "Dividend Yield",
  "Asset Turnover",
  "Interest Coverage",
  "EBITDA Margins",
  "Singapore Market",
  "Malaysia Market",
  "Indonesia Market",
  "Thailand Market",
  "Vietnam Market",
  "Philippines Market",
  "South Korea Market",
  "Taiwan Market",
  "Australia Market",
  "New Zealand Market",
  "Dubai Market",
  "Saudi Market",
  "Qatar Market",
  "South Africa Market",
  "Brazil Market",
  "Auto Components",
  "Cement Industry",
  "Chemical Industry",
  "Consumer Durables",
  "Fertilizers",
  "Food Processing",
  "Glass Industry",
  "Hotel Industry",
  "Paint Industry",
  "Paper Industry",
  "Rubber Industry",
  "Sugar Industry",
  "Tobacco Industry",
  "White Goods",
  "Wine Spirits",
  "Currency Markets",
  "Foreign Exchange",
  "Currency Derivatives",
  "Currency Options",
  "Currency Futures",
  "Forex Trading",
  "Currency Volatility",
  "Exchange Rates",
  "Currency Hedging",
  "Currency Risk",
  "Dollar Index",
  "Currency Pairs",
  "Cross Rates",
  "Currency Interventions",
  "Currency Regulations",
  "SME Sector",
  "MSME Finance",
  "SME Growth",
  "MSME Policy",
  "Small Business",
  "Medium Enterprises",
  "SME Banking",
  "MSME Loans",
  "SME Exports",
  "MSME Technology",
  "SME Employment",
  "MSME Schemes",
  "SME Registration",
  "MSME Innovation",
  "SME Development",
  "Green Energy",
  "Sustainable Finance",
  "Carbon Credits",
  "Climate Change",
  "Renewable Power",
  "Solar Energy",
  "Wind Energy",
  "Clean Technology",
  "Green Buildings",
  "Waste Management",
  "Water Management",
  "Sustainable Agriculture",
  "Green Transport",
  "Circular Economy",
  "Environmental Compliance",
  "IT Services",
  "Consulting Services",
  "Financial Services",
  "Legal Services",
  "Audit Services",
  "Marketing Services",
  "HR Services",
  "Business Process",
  "Cloud Services",
  "Data Services",
  "Security Services",
  "Facility Management",
  "Professional Services",
  "Advisory Services",
  "Outsourcing Services",
  "Retail Sector",
  "E Commerce",
  "Consumer Brands",
  "Luxury Market",
  "Fashion Industry",
  "Food Beverage",
  "Personal Care",
  "Home Care",
  "Consumer Electronics",
  "Online Shopping",
  "Retail Chains",
  "Consumer Trends",
  "Shopping Malls",
  "Direct Selling",
  "Consumer Credit",
];

export const TYPEMAPPING = {
  US_Equity: "us",
  Indian_Equity: "indian",
  Forex: "forex",
  Crypto: "crypto",
};

export const REVERSE_TYPE_MAPPING = {
  us: "US_Equity",
  indian: "Indian_Equity",
  forex: "Forex",
  crypto: "Crypto",
};

export const STRATEGY_CATEGORIES = [
  {
    label: "Price-Based",
    value: "price",
    description: "Strategies based on price action and technical patterns",
    icon: PriceBased,
  },
  {
    label: "Volume-Based",
    value: "volume",
    description: "Strategies focusing on trading volume patterns and analysis",
    icon: VolumeBased,
  },
  {
    label: "Volatility-Based",
    value: "volatility",
    description: "Strategies levaraging market volatility indicators",
    icon: VolatilityBased,
  },
  {
    label: "Statistical",
    value: "statistical",
    description: "Strategies based on statistical analysis and probability",
    icon: Statistical,
  },
  {
    label: "Momentum-Based",
    value: "momentum",
    description: "Strategies utilizing time patterns and seasonal effects",
    icon: MomentumBased,
  },
  {
    label: "Combined Signals",
    value: "Combination",
    description: "Advanced strategies combining multiple indicators",
    icon: CombinedSignals,
  },
];

export const LOOKBACK_PERIOD_OPTIONS = [
  { value: "2h", label: "2hr" },
  { value: "4h", label: "4hr" },
  { value: "8h", label: "8hr" },
  { value: "24h", label: "24hr" },
  { value: "720h", label: "1 Month" },
];

export const MARKETS = [
  { label: "Indian Equity", value: "Indian_Equity" },
  { label: "US Equity", value: "US_Equity" },
  { label: "Crypto", value: "Crypto" },
  { label: "Forex", value: "Forex" },
];

export const TIME_FRAMES = [
  // { label: "5 Minutes", value: "5m" },
  { label: "10 Minutes", value: "10m" },
  { label: "15 Minutes", value: "15m" },
  { label: "30 Minutes", value: "30m" },
  { label: "1 Hour", value: "1h" },
  { label: "24 Hours", value: "1D" },
  { label: "1 Week", value: "1W" },
  { label: "1 Month", value: "1M" },
];

export const CONTRACT_TYPES = [
  { label: "Stock", value: "STOCK" },
  { label: "Futures", value: "FUTURES" },
  { label: "Options", value: "OPTIONS" },
];

export const OPERATORS = [
  { label: "Equal to", value: "eq", symbol: "=" },
  { label: "Greater than", value: "gt", symbol: ">" },
  { label: "Greater than or equal to", value: "gte", symbol: "≥" },
  { label: "Less than", value: "lt", symbol: "<" },
  { label: "Less than or equal to", value: "lte", symbol: "≤" },
];

export const PATTERN_SIGNALS_SECTIONS = [
  {
    title: "Single Candlesticks",
    key: "singleCandlesticks",
    addButtonText: "Add Single Candlesticks",
    category: "Single Candlesticks",
  },
  {
    title: "Double Candlesticks",
    key: "doubleCandlesticks",
    addButtonText: "Add Double Candlesticks",
    category: "Double Candlesticks",
  },
  {
    title: "Triple Candlesticks",
    key: "tripleCandlesticks",
    addButtonText: "Add Triple Candlesticks",
    category: "Triple Candlesticks",
  },
  {
    title: "Basic Patterns",
    key: "basicPatterns",
    addButtonText: "Add Basic Patterns",
    category: "Basic Patterns",
  },
  {
    title: "Advance Patterns",
    key: "advancedPatterns",
    addButtonText: "Add Advance Patterns",
    category: "Advanced Patterns",
  },
  {
    title: "Harmonic Patterns",
    key: "harmonicPatterns",
    addButtonText: "Add Harmonic Patterns",
    category: "Harmonic Patterns",
  },
];

export const PATTERN_TYPES = [
  "Single Candlesticks",
  "Double Candlesticks",
  "Triple Candlesticks",
  "Basic Patterns",
  "Advanced Patterns",
  "Harmonic Patterns",
];

export const DEFAULT_TRENDS = [
  { label: "Bullish", value: "bullish" },
  { label: "Bearish", value: "bearish" },
];

export const COMPARISON_OPERATOR = ["value", "indicator"];

export const MARKET_IDENTIFIER = {
  Indicator: "indicators",
  Strategy: "strategy",
  Pattern: "strategies",
};

export const SCREENER = {
  MAX_GROUPS: 10,
  MAX_CONDITIONS_PER_GROUP: 10,
  MAX_NESTED_CONDITIONS_PER_GROUP: 1,
  DEFAULT_LOOPBACK_PERIOD: "24h",
  DEFAULT_TIMEFRAME: "1h",
};

export const CACHE = {
  MARLET_CLOSE_DATA_EXPIRY_TIME: 6 * 60 * 60 * 1000,
  MARLET_CLOSE_DATA_KEY: "market_close_data_cache",
};

export const CUSTOM_STRATEGY_TEMPLATE = [
  {
    name: "golden_crossover_strategy",
    label: "Golden Crossover Strategy",
    description: "Trade momentum when short-term MA crosses above long-term MA",
    groups: [
      {
        condition: "",
        rules: [
          {
            key: "indicators",
            attribute: "sma_50",
            operator: "gt",
            fieldExpression: "indicator",
            value: "sma_200",
            nested: null,
            nestedOperator: "",
            conditionOperator: "",
          },
        ],
      },
    ],
  },
  {
    name: "rsi_oversold",
    label: "RSI Oversold",
    description:
      "Identify potential reversals by entering when market becomes oversold",
    groups: [
      {
        condition: "",
        rules: [
          {
            key: "indicators",
            attribute: "rsi_14",
            operator: "lt",
            fieldExpression: "value",
            value: "30",
            nested: null,
            nestedOperator: "",
            conditionOperator: "",
          },
        ],
      },
    ],
  },
  {
    name: "triple_ema_crossover",
    label: "Triple EMA Crossover",
    description: "Confirm strong trends with three exponential moving averages",
    groups: [
      {
        condition: "",
        rules: [
          {
            key: "indicators",
            attribute: "ema_5",
            operator: "gt",
            fieldExpression: "indicator",
            value: "ema_13",
            nested: null,
            nestedOperator: "",
            conditionOperator: "",
          },
          {
            key: "indicators",
            attribute: "ema_5",
            operator: "gt",
            value: "ema_26",
            nested: null,
            nestedOperator: "",
            conditionOperator: "and",
            fieldExpression: "indicator",
          },
          {
            key: "indicators",
            attribute: "ema_13",
            operator: "gt",
            value: "ema_26",
            nested: null,
            nestedOperator: "",
            conditionOperator: "and",
            fieldExpression: "indicator",
          },
        ],
      },
    ],
  },
  {
    name: "stochastic_crossover_strategy",
    label: "Stochastic Crossover strategy",
    description:
      "Capture reversals when stochastic lines cross in extreme zones",
    groups: [
      {
        condition: "",
        rules: [
          {
            key: "indicators",
            attribute: "stoch_14_K",
            operator: "gt",
            fieldExpression: "indicator",
            value: "stoch_5_D",
            nested: null,
            nestedOperator: "",
            conditionOperator: "",
          },
          {
            key: "indicators",
            attribute: "stoch_14_K",
            operator: "lt",
            value: "20",
            nested: null,
            nestedOperator: "",
            conditionOperator: "and",
            fieldExpression: "value",
          },
          {
            key: "indicators",
            attribute: "stoch_5_D",
            operator: "lt",
            value: "20",
            nested: null,
            nestedOperator: "",
            conditionOperator: "and",
            fieldExpression: "value",
          },
        ],
      },
    ],
  },
  {
    name: "adx_(average_directional_index)_strategy",
    label: "ADX (Average Directional Index) Strategy",
    description: "Trade only strong directional trends for higher probability",
    groups: [
      {
        condition: "",
        rules: [
          {
            key: "indicators",
            attribute: "adx_14",
            operator: "gt",
            fieldExpression: "value",
            value: "25",
            nested: null,
            nestedOperator: "",
            conditionOperator: "",
          },
          {
            key: "indicators",
            attribute: "di_plus_14",
            operator: "gt",
            value: "di_minus_14",
            nested: null,
            nestedOperator: "",
            conditionOperator: "and",
            fieldExpression: "indicator",
          },
        ],
      },
    ],
  },
  {
    name: "parabolic_sar_strategy",
    label: "Parabolic SAR Strategy",
    description: "Follow trends with automatic stop and reverse signals",
    groups: [
      {
        condition: "",
        rules: [
          {
            key: "indicators",
            attribute: "close",
            operator: "gt",
            fieldExpression: "indicator",
            value: "psar",
            nested: null,
            nestedOperator: "",
            conditionOperator: "",
          },
        ],
      },
    ],
  },
  {
    name: "bullish_engulfing_+_rsi_confirmation",
    label: "Bullish Engulfing + RSI Confirmation",
    description: "Combine candlestick patterns with momentum confirmation",
    groups: [
      {
        condition: "",
        rules: [
          {
            key: "patterns",
            attribute: "engulfing_pattern",
            operator: "",
            fieldExpression: "",
            value: "bullish",
            nested: null,
            nestedOperator: "",
            conditionOperator: "",
            category: "Double Candlesticks",
          },
          {
            key: "indicators",
            attribute: "rsi_14",
            operator: "lt",
            value: "30",
            nested: null,
            nestedOperator: "",
            conditionOperator: "and",
            fieldExpression: "value",
          },
        ],
      },
    ],
  },
  // {
  //   name: "double_bottom_+_moving_average_support_strategy",
  //   label: "Double Bottom + Moving Average Support Strategy",
  //   description: "Enter reversal patterns with technical support validation",
  //   groups: [
  //     {
  //       condition: "",
  //       rules: [
  //         {
  //           key: "patterns",
  //           attribute: "double_bottoms",
  //           operator: "",
  //           fieldExpression: "",
  //           value: "bullish",
  //           nested: null,
  //           nestedOperator: "",
  //           conditionOperator: "",
  //           category: "Advanced Patterns",
  //         },
  //         {
  //           key: "indicators",
  //           attribute: "ema_20",
  //           operator: "gt",
  //           value: "ema_50",
  //           nested: null,
  //           nestedOperator: "",
  //           conditionOperator: "and",
  //           fieldExpression: "indicator",
  //         },
  //         {
  //           key: "indicators",
  //           attribute: "close",
  //           operator: "gt",
  //           value: "ema_50",
  //           nested: null,
  //           nestedOperator: "",
  //           conditionOperator: "and",
  //           fieldExpression: "indicator",
  //         },
  //       ],
  //     },
  //   ],
  // },
];

export const DASHBOARD = {
  NEWS_MAX_VISIBLE_PAGES: 5,
  STOCK_SCAN_LOOKBACK_PERIOD: "72h",
  INDIAN_EQUITY_CHART: {
    "BAJAJ-AUTO": "BAJAJ_AUTO",
    "NIFTY BANK": "",
    "NIFTY 50": "",
    "S&SPOWER-BE": "",
    "MITCONPP-E1": "",
    "NITCO-BE": "NITCO",
    "AAREYDRUGS-BE": "AAREYDRUGS",
    "ABNINT-IT": "",
  },
  STOCK_SCAN: [
    {
      label: "RSI oversold",
      description: "Potential reversal from oversold conditions",
      movement: 0,
      count: 0,
      group: [
        {
          condition: "",
          rules: [
            {
              key: "indicators",
              attribute: "rsi_14",
              operator: "lt",
              fieldExpression: "value",
              value: "30",
              nested: null,
              nestedOperator: "",
              conditionOperator: "",
            },
          ],
        },
      ],
    },
    {
      label: "Head and Shoulder Pattern",
      description: "Major reversal after uptrend completion",
      movement: -1,
      count: 0,
      group: [
        {
          condition: "",
          rules: [
            {
              key: "patterns",
              attribute: "head_and_shoulder",
              operator: "",
              fieldExpression: "",
              value: "bearish",
              nested: null,
              nestedOperator: "",
              conditionOperator: "",
              category: "Advanced Patterns",
            },
          ],
        },
      ],
    },
    {
      label: "Bullish Closing Marubozu",
      description: "Strong Bullish conviction candle showing dominance",
      movement: 1,
      count: 0,
      group: [
        {
          condition: "",
          rules: [
            {
              key: "patterns",
              attribute: "closing_marubozu",
              operator: "",
              fieldExpression: "",
              value: "bullish",
              nested: null,
              nestedOperator: "",
              conditionOperator: "",
              category: "Single Candlesticks",
            },
          ],
        },
      ],
    },
    {
      label: "Bearish Closing Marubozu",
      description: "Strong Bearish conviction candle showing dominance",
      movement: -1,
      count: 0,
      group: [
        {
          condition: "",
          rules: [
            {
              key: "patterns",
              attribute: "closing_marubozu",
              operator: "",
              fieldExpression: "",
              value: "bearish",
              nested: null,
              nestedOperator: "",
              conditionOperator: "",
              category: "Single Candlesticks",
            },
          ],
        },
      ],
    },
    {
      label: "Golden Cross Strategy",
      description: "Long-term moving average trend change to Bullish",
      movement: 1,
      count: 0,
      group: [
        {
          condition: "",
          rules: [
            {
              key: "strategies",
              attribute: "golden_cross_over_strategy",
              operator: "",
              fieldExpression: "",
              value: "bullish",
              nested: null,
              nestedOperator: "",
              conditionOperator: "",
              category: "price",
            },
          ],
        },
      ],
    },
    {
      label: "Death Cross Strategy",
      description: "Long-term moving average trend change to Bearish",
      movement: -1,
      count: 0,
      group: [
        {
          condition: "",
          rules: [
            {
              key: "strategies",
              attribute: "golden_cross_over_strategy",
              operator: "",
              fieldExpression: "",
              value: "bearish",
              nested: null,
              nestedOperator: "",
              conditionOperator: "",
              category: "price",
            },
          ],
        },
      ],
    },
    {
      label: "Double Top",
      description: "Price forms an M-shape, indicating potential reversal",
      movement: -1,
      count: 0,
      group: [
        {
          condition: "",
          rules: [
            {
              key: "patterns",
              attribute: "double_tops",
              operator: "",
              fieldExpression: "value",
              value: "bearish",
              nested: null,
              nestedOperator: "",
              conditionOperator: "",
              category: "Advanced Patterns",
            },
          ],
        },
      ],
    },
    {
      label: "Golden Hammer",
      description: "Hammer candlestick with oversold conditions",
      movement: 1,
      count: 0,
      group: [
        {
          condition: "",
          rules: [
            {
              key: "patterns",
              attribute: "hammer",
              operator: "",
              fieldExpression: "",
              value: "bullish",
              nested: null,
              nestedOperator: "",
              conditionOperator: "",
              category: "Single Candlesticks",
            },
            {
              key: "indicators",
              attribute: "rsi_14",
              operator: "lt",
              value: "30",
              nested: null,
              nestedOperator: "",
              conditionOperator: "and",
              fieldExpression: "value",
            },
          ],
        },
      ],
    },
    {
      label: "Bullish Engulfing",
      description: "Previous downtrend completely overtaken/reversed",
      movement: 1,
      count: 0,
      group: [
        {
          condition: "",
          rules: [
            {
              key: "patterns",
              attribute: "engulfing_pattern",
              operator: "",
              fieldExpression: "",
              value: "bullish",
              nested: null,
              nestedOperator: "",
              conditionOperator: "",
              category: "Double Candlesticks",
            },
          ],
        },
      ],
    },
    {
      label: "Bearish Engulfing",
      description: "Previous uptrend completely overtaken/reversed",
      movement: -1,
      count: 0,
      group: [
        {
          condition: "",
          rules: [
            {
              key: "patterns",
              attribute: "engulfing_pattern",
              operator: "",
              fieldExpression: "",
              value: "bearish",
              nested: null,
              nestedOperator: "",
              conditionOperator: "",
              category: "Double Candlesticks",
            },
          ],
        },
      ],
    },
    {
      label: "Double Bottom",
      description: "Price forms a W-shape, indicating potential reversal",
      movement: 1,
      count: 0,
      group: [
        {
          condition: "",
          rules: [
            {
              key: "patterns",
              attribute: "double_bottoms",
              operator: "",
              fieldExpression: "value",
              value: "bullish",
              nested: null,
              nestedOperator: "",
              conditionOperator: "",
              category: "Advance Patterns",
            },
          ],
        },
      ],
    },
    {
      label: "Bullish Flag Pattern",
      description: "Brief consolidation before uptrend continuation",
      movement: 1,
      count: 0,
      group: [
        {
          condition: "",
          rules: [
            {
              key: "patterns",
              attribute: "bullish_flag",
              operator: "",
              fieldExpression: "",
              value: "bullish",
              nested: null,
              nestedOperator: "",
              conditionOperator: "",
              category: "Basic Patterns",
            },
          ],
        },
      ],
    },
    {
      label: "Bearish Flag Pattern",
      description: "Brief consolidation before downtrend continuation",
      movement: -1,
      count: 0,
      group: [
        {
          condition: "",
          rules: [
            {
              key: "patterns",
              attribute: "bearish_flag",
              operator: "",
              fieldExpression: "",
              value: "bearish",
              nested: null,
              nestedOperator: "",
              conditionOperator: "",
              category: "Basic Patterns",
            },
          ],
        },
      ],
    },
    {
      label: "Three White Soldiers",
      description: "Strong bullish reversal pattern",
      movement: 1,
      count: 0,
      group: [
        {
          condition: "",
          rules: [
            {
              key: "patterns",
              attribute: "three_white_soldiers",
              operator: "",
              fieldExpression: "",
              value: "bullish",
              nested: null,
              nestedOperator: "",
              conditionOperator: "",
              category: "Triple Candlesticks",
            },
          ],
        },
      ],
    },
    {
      label: "Three Black Crows",
      description: "Strong bearish reversal pattern",
      movement: -1,
      count: 0,
      group: [
        {
          condition: "",
          rules: [
            {
              key: "patterns",
              attribute: "three_black_crows",
              operator: "",
              fieldExpression: "",
              value: "bearish",
              nested: null,
              nestedOperator: "",
              conditionOperator: "",
              category: "Triple Candlesticks",
            },
          ],
        },
      ],
    },
    {
      label: "Bollinger Band Strategy",
      description: "Volatility contraction before explosive movement",
      movement: -1,
      count: 0,
      group: [
        {
          condition: "",
          rules: [
            {
              key: "strategies",
              attribute: "bollinger_bands_strategy",
              operator: "",
              fieldExpression: "",
              value: "bullish",
              nested: null,
              nestedOperator: "",
              conditionOperator: "",
              category: "volatility",
            },
            {
              key: "strategies",
              attribute: "bollinger_bands_strategy",
              operator: "",
              value: "bearish",
              nested: null,
              nestedOperator: "",
              conditionOperator: "or",
              category: "volatility",
            },
          ],
        },
      ],
    },
  ],
};

export const SIGNAL_STRENGTHS = ["Moderate", "Weak", "Strong"];

export const PRICE_ALERT_OPTIONS = [
  { label: "Crossing", value: "crossing", symbol: crossing },
  { label: "Crossing Up", value: "crossing_up", symbol: crossingUp },
  { label: "Crossing Down", value: "crossing_down", symbol: crossingDown },
  // { label: "Greater Than", value: "greater_than", symbol: ">" },
  // { label: "Less Than", value: "less_than", symbol: "<" },
  // {
  //   label: "Entering Channel",
  //   value: "entering_channel",
  //   symbol: enteringChannel,
  // },
  // {
  //   label: "Exiting Channel",
  //   value: "exiting_channel",
  //   symbol: exitingChannel,
  // },
  // { label: "Inside Channel", value: "inside_channel", symbol: "↕" },
  // { label: "Outside Channel", value: "outside_channel", symbol: "⋮" },
  // { label: "Moving Up", value: "moving_up", symbol: MovingUp },
  // { label: "Moving Down", value: "moving_down", symbol: MovingDown },
  // {
  //   label: "Moving Up %",
  //   value: "moving_up_percent",
  //   symbol: MovingPercentageUp,
  // },
  // {
  //   label: "Moving Down %",
  //   value: "moving_down_percent",
  //   symbol: MovingPercentageDown,
  // },
];

export const PRICE_ALERT_INTERVALS = [
  { label: "3 Minutes", value: "3m" },
  { label: "5 Minutes", value: "5m" },
  { label: "10 Minutes", value: "10m" },
  { label: "15 Minutes", value: "15m" },
  { label: "30 Minutes", value: "30m" },
  { label: "1 Hour", value: "1h" },
  { label: "24 Hours", value: "1D" },
];
